import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  mainContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: '5%',
  },
  productContainer: {
    width: '47%',
    marginBottom: 10,
  },
  productImageContainer: {
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    height: 170,
  },
  heartIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  productImage: {
    height: 150,
    width: 150,
  },
  cartProductImage: {
    height: 80,
    width: 80,
  },
  productDetails: {
    marginTop: 10,
  },
  productName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: '#000',
  },
  productPrice: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f4a244',
  },
  buyButton: {
    width: 42,
    borderWidth: 1,
    borderColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    borderRadius: 7,
    padding: 4,
  },
  buyButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  bottomNav: {
    height: 70,
    borderColor: '#858585',
    backgroundColor: '#fff',
  },
  bottomNavContent: {
    flexDirection: 'row',
    width: '50%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  safeArea: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#000',
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  headerIcons: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: '35%',
  },
  recommendationSection: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
  },
  recommendationTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  recommendationIcon: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  productList: {
    width: '100%',
    marginTop: 10,
    marginBottom: '15%',
  },
  columnWrapper: {
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  cartItemContainer: {
    width: '100%',
    marginTop: 14,
    padding: 8,
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#dcfae7',
    gap: 8,
  },
  cartItemContainerAlt: {
    width: '100%',
    marginTop: 14,
    padding: 8,
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#f5ebff',
    gap: 8,
  },
  cartItemImageContainer: {
    flex: 0.25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#ffffffff',
  },
  cartItemDetails: {
    flex: 0.75,
    paddingHorizontal: 10,
  },
  cartItemName: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  cartItemDescription: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#575757ff',
  },
  cartItemPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cartItemPrice: {
    fontSize: 20,
    fontWeight: 'bold',
    flex: 0.5,
  },
  cartQuantityContainer: {
    flex: 0.3,
    backgroundColor: '#fff',
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 30,
  },
  cartQuantityText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalContainer: {
    width: '100%',
    height: 200,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
  },
  addToCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    width: 60,
    borderWidth: 1,
    borderColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    borderRadius: 7,
    padding: 4,
    gap: 6,
  },
  cartTotalContainer: {
    position: 'absolute',
    bottom: 50,
    width: '100%',
    padding: 10,
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#fff0c9',
    borderColor: '#000',
    borderWidth: 0.5,
    gap: 8,
  },
  cartTotalText: {
    fontSize: 20,
    fontWeight: 'bold',
    flex: 0.5,
  },
  checkoutButton: {
    width: '100%',
    marginTop: 10,
    padding: 8,
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#dcfae7',
    gap: 8,
  },
  checkoutButton: {
    width: '100%',
    marginTop: 10,
    padding: 8,
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#dcfae7',
    gap: 8,
  },
  checkoutButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    flex: 0.5,
  },
  productPageHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 5,
    marginBottom: 10,
  },
  productPageImageContainer: {
    width: '100%',
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    marginBottom: 20,
  },
  productPageImage: {
    width: 250,
    height: 250,
    resizeMode: 'contain',
  },
  productPageInfo: {
    paddingHorizontal: 10,
    flex: 1,
    width: '100%',
  },
  productPageFooter: {
    paddingHorizontal: 10,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  productPageName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 5,
  },
  productPagePrice: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#f4a244',
    marginBottom: 15,
  },
  productPageDescription: {
    fontSize: 16,
    color: '#575757',
    lineHeight: 24,
    marginBottom: 20,
  },
  productPageBuyButton: {
    width: '100%',
    backgroundColor: '#000',
    padding: 15,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productPageBuyButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  productPageQtyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f0f0f0',
    borderRadius: 15,
    width: 140,
    padding: 10,
  },
});
